MovieApp.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Web.Models;
using System.Collections.Generic;
using System.Linq;
using MovieApp.Web.Data;
using MovieApp.Web.Entity;

namespace MovieApp.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly MovieContext _context;

        public HomeController(MovieContext movieContext)
        {
            _context = movieContext;
        }


        public IActionResult Index()
        {
            var model = new HomePageViewModel()
            {
                //PopularMovies = MovieRepository.Movies
                PopularMovies = _context.Movies.ToList()
            };

            return View(model);
        }

        public IActionResult About()
        {
            
            return View();
        }
    }
}

MovieApp.Web/ViewComponents/GenresViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Web.Models;
using System.Collections.Generic;
using System.Linq;
using MovieApp.Web.Data;

namespace MovieApp.Web.ViewComponents
{
    public class GenresViewComponent: ViewComponent
    {
        private readonly MovieContext _context;

        public GenresViewComponent(MovieContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedGenreID = RouteData.Values["id"];
            return View(_context.Genres.ToList());
        }
    }
}

MovieApp.Web/Views/Home/About.cshtml
 @model List<Genre>
<p>Home/About</p> 

@section menu 
{
    @await Component.InvokeAsync("Genres")
}
        

MovieApp.Web/Views/Home/Index.cshtml
@model HomePageViewModel

@{
    Layout = "_Layout2";
}

@section header
{
    @await Html.PartialAsync("_header")
}

<h1>Örnek Film Gösterimi</h1>
<div id="filmler">
    @foreach (var movie in Model.PopularMovies)
    {
        @await Html.PartialAsync("_movie", movie)
    }
</div>